(function() {
	"use strict";
	var CBM = window.CBM = window.CBM || {};
	CBM.language = {
		bnk_01 : "기업은행",
		bnk_02 : "국민은행",
		bnk_03 : "외환은행",
		bnk_04 : "수협중앙회",
		bnk_05 : "농협중앙회",
		bnk_06 : "우리은행",
		bnk_07 : "SC 제일은행",
		bnk_08 : "대구은행",
		bnk_09 : "부산은행",
		bnk_10 : "광주은행",
		bnk_11 : "전북은행",
		bnk_12 : "경남은행",
		bnk_13 : "한국씨티은행",
		bnk_14 : "우체국",
		bnk_15 : "하나은행",
		bnk_16 : "신한은행",

		crd_01 : "외환카드",
		crd_02 : "롯데카드",
		crd_03 : "현대카드",
		crd_04 : "KB카드",
		crd_05 : "BC카드",
		crd_06 : "삼성카드",
		crd_07 : "신한카드",
		crd_08 : "NH카드",
		crd_09 : "하나SK카드",

		des_01 : "이제 사진을 놓으세요!",
		des_02 : "사진을 여기로 끌어오세요!",
		des_03 : "내가 디자인한 케이스!",
		des_51 : "작업한 내용이 모두 초기화 됩니다. 진행하시겠습니까?",
		des_52 : "장바구니에 등록되었습니다.<br/>장바구니로 이동하시겠습니까?",
		des_61 : "페이스북에 공유되었습니다.",
		des_62 : "갤럭시S2는 SKT,KT에서 출시 된 3G 모델만 호환 됩니다.<br/>(HD, LTE모델, LG모델은 호환되지 않습니다.)",
		des_71 : "20MB 이하의 파일만 업로드 가능합니다.",
		des_72 : "사진을 전부 넣어주세요",
		des_73 : "죄송합니다. 서버와의 통신에 문제가 발생하였습니다. 다시 시도해주세요.",
		des_80 : "갤럭시 <b>노트3</b> 모델입니다.<br/>갤럭시 <b>노트3 Neo</b> 모델은 호환 되지 않습니다.",
		des_81 : "LG <b>G3 & G3 cat6 </b>모델 입니다.<br/>LG <b>G3 screen, beat, style</b> 모델과 호환되지 않습니다.",
		des_82 : "갤럭시 <b>A5 2015</b> 모델입니다.<br/>갤럭시 <b>A5 2016</b> 모델과 호환 되지 않습니다.",
		des_83 : "갤럭시 <b>A7 2015</b> 모델입니다.<br/>갤럭시 <b>A7 2016</b> 모델과 호환 되지 않습니다.",
		des_84 : "갤럭시 <b>A8 2015</b> 모델입니다.<br/>갤럭시 <b>A8 2016</b> 모델과 호환 되지 않습니다.",
		des_85 : "갤럭시 <b>A5 2016</b> 모델입니다.<br/>갤럭시 <b>A5 2015</b> 모델과 호환 되지 않습니다.",
		des_86 : "갤럭시 <b>A7 2016</b> 모델입니다.<br/>갤럭시 <b>A7 2015</b> 모델과 호환 되지 않습니다.",
		des_87 : "갤럭시 <b>J5 2015</b> 모델입니다.<br/>갤럭시 <b>J5 2016</b> 모델과 호환 되지 않습니다.",
		des_88 : "갤럭시 <b>J7 2015</b> 모델입니다.<br/>갤럭시 <b>J7 2016</b> 모델과 호환 되지 않습니다.",
		des_89 : "갤럭시 <b>J5 2016</b> 모델입니다.<br/>갤럭시 <b>J5 2015</b> 모델과 호환 되지 않습니다.",
		des_90 : "갤럭시 <b>J7 2016</b> 모델입니다.<br/>갤럭시 <b>J7 2015</b> 모델과 호환 되지 않습니다.",

		fil_01 : "원본",
		fil_02 : "뽀샤시",
		fil_03 : "흑백",
		fil_04 : "세피아",
		fil_05 : "샌 카멘",
		fil_06 : "스트라토",
		fil_07 : "비비드",
		fil_08 : "인디글로우",
		fil_09 : "아쿠아",
		fil_10 : "라구나",

		gal_51 : "삭제하시겠습니까?",
		gal_61 : "페이스북에 공유되었습니다.",
		gal_62 : "장바구니에 등록되었습니다.",

		gen_01 : "원",
		gen_02 : "개",
		gen_03 : "합계",
		gen_04 : "페이스북으로 로그인",
		gen_05 : "비회원 주문조회",
		gen_06 : "비회원 장바구니",
		gen_07 : "로그인 / 조회",
		gen_08 : "주문조회",
		gen_09 : "장바구니",
		gen_10 : "갤러리",
		gen_11 : "로그아웃",
		gen_71 : "ㅠ.ㅠ",

		ie8_71 : "explorer 8은 한장 레이아웃만 지원합니다.",
		ie8_72 : "이미지 불러오기에 실패했습니다",

		lay_01 : "여덟장",
		lay_02 : "다섯장",
		lay_03 : "네장",
		lay_04 : "세장",
		lay_05 : "두장",
		lay_06 : "두장+하트",
		lay_07 : "한장",
		lay_08 : "네장+하트",
		lay_09 : "아홉장",

		pur_01 : "대한통운",
		pur_02 : "페이스북 좋아요 쿠폰",
		pur_03 : "프로모션 쿠폰",
		pur_04 : "예금주 : 케이스바이미",
		pur_05 : "입금기한",
		pur_06 : "계좌이체",
		pur_07 : "휴대폰 결제",
		pur_08 : "무료 쿠폰 사용",
		pur_09 : "회원분은 갤러리에서 케이스를 다시 확인하실 수 있습니다.",
		pur_10 : "주문취소<br/>(입금기한초과)",
		pur_51 : "장바구니에서 삭제하시겠습니까?",
		pur_52 : "해당 페이지를 벗어나면 작성하신 정보는 저장되지 않습니다. 이동 하시겠습니까?",
		pur_61 : "아직 Caseby.me 페이스북 페이지 \'좋아요\' 버튼을 누르지 않으셨네요.<br/><br/>\'좋아요\'를 누르고 5,000원도 할인 받아보시겠어요?",
		pur_62 : "페이스북 좋아요 쿠폰을 적용 하시겠습니까?",
		pur_71 : "쿠폰코드를 입력해주세요",
		pur_72 : "페이스북 로그인에 실패하였습니다.",
		pur_73 : "주문번호를 입력해주세요",
		pur_74 : "해당 주문정보를 찾을 수 없습니다.",
		pur_75 : "주소를 넣어주세요",
		pur_76 : "주소 검색 결과가 없습니다.",
		pur_77 : "이름을 적어주세요!",
		pur_78 : "이메일이 없습니다. 결제결과 통보를 받으실 이메일주소를 입력해 주세요.",
		pur_79 : "휴대폰번호는 숫자만 입력가능합니다.",
		pur_80 : "연락처를 적어주세요!",
		pur_81 : "받으시려는 배송지 주소를 적어주세요!",
		pur_82 : "결제가 완료되지 않았습니다.",
		pur_83 : "계좌이체는 모바일 기기에서 지원하지 않습니다.",
		pur_84 : "결제 정보를 찾을 수 없습니다.",

		sta_01 : "결제 중",
		sta_02 : "결제 완료",
		sta_03 : "제작 중",
		sta_04 : "배송 준비",
		sta_05 : "배송 중",
		sta_06 : "배송 중",
		sta_07 : "주문 취소",

		delivery_price : 2500, // find keyword delivery
		price : 21900,
		language : 'kr',

		delivery_k001 : 'CJ대한통운',
		delivery_k002 : '로젠택배',
		delivery_k003 : '현대택배',
		delivery_k004 : '경동택배',
		delivery_k005 : '대신택배',
		delivery_k006 : '대한항공',
		delivery_k007 : '동부택배',
		delivery_k008 : '범한판토스',
		delivery_k009 : '우체국택배',
		delivery_k010 : '이노지스택배',
		delivery_k011 : '일양로지스택배',
		delivery_k012 : '한덱스',
		delivery_k013 : '한의사랑택배',
		delivery_k014 : '한진택배',
		delivery_k015 : 'CVSnet 편의점택배',
		delivery_k016 : 'EMS',
		delivery_k017 : 'FedEx',
		delivery_k018 : 'KG옐로우캡택배',
		delivery_k019 : 'KGB택배',
		delivery_k020 : 'OCS 택배',
		delivery_k021 : 'TNT Express',
		delivery_k022 : 'UPS',
		delivery_k023 : 'DHL',
		delivery_k024 : '하나로택배',
		delivery_k025 : 'HB한방택배',
		delivery_k026 : '호남택배',
		delivery_ex01 : 'EMS',

		link_k001 : 'https://www.doortodoor.co.kr/parcel/doortodoor.do?fsp_action=PARC_ACT_002&fsp_cmd=retrieveInvNoACT&invc_no=',
		link_k002 : 'http://www.ilogen.com/iLOGEN.Web.New/TRACE/TraceView.aspx?gubun=slipno&slipno=',
		link_k003 : 'http://www.hlc.co.kr/personalService/tracking/06/tracking_goods_result.jsp?InvNo=',
		link_k004 : 'http://www.kdexp.com/sub4_1.asp?stype=1&p_item=',
		link_k005 : 'http://home.daesinlogistics.co.kr/daesin/jsp/d_freight_chase/d_general_process2.jsp?',
		link_k006 : 'http://cargo.koreanair.com/ecus/trc/servlet/TrackingServlet?pid=5&version=kor&menu1=m1&menu2=m01-1&awb_no=',
		link_k007 : 'http://www.dongbups.com/delivery/delivery_search_view.jsp?item_no=',
		link_k008 : 'http://www.epantos.com/jsp/gx/tracking/tracking/trackingInquery.jsp?refNo=',
		link_k009 : 'http://service.epost.go.kr/trace.RetrieveRegiPrclDeliv.postal?sid1=',
		link_k010 : 'http://www.innogis.net/trace02.asp?invoice=',
		link_k011 : 'http://www.ilyanglogis.com/functionality/tracking_result.asp?hawb_no=',
		link_k012 : 'http://btob.sedex.co.kr/work/app/tm/tmtr01/tmtr01_s4.jsp?IC_INV_NO=',
		link_k013 : 'http://www.hanips.com/html/sub03_03_1.html?logicnum=',
		link_k014 : 'http://www.hanjin.co.kr/Delivery_html/inquiry/result_waybill.jsp?wbl_num=',
		link_k015 : 'http://was.cvsnet.co.kr/_ver2/board/ctod_status.jsp?invoice_no=',
		link_k016 : 'http://service.epost.go.kr/trace.RetrieveEmsTrace.postal?ems_gubun=E&POST_CODE=',
		link_k017 : 'http://www.fedex.com/Tracking?ascend_header=1&clienttype=dotcomreg&cntry_code=kr&language=korean&tracknumbers=',
		link_k018 : 'http://www.yellowcap.co.kr/iframe-delivery.html?delivery=',
		link_k019 : 'http://www.kgbls.co.kr/sub5/trace.asp?f_slipno=',
		link_k020 : 'http://www.ocskorea.com/online_bl_multi.asp?mode=search&search_no=',
		link_k021 : 'http://www.tnt.com/webtracker/tracking.do?respCountry=kr&respLang=ko&searchType=CON&cons=',
		link_k022 : 'http://www.ups.com/WebTracking/track?loc=ko_KR&InquiryNumber1=',
		link_k023 : 'http://www.dhl.co.kr/publish/kr/ko/eshipping/track.high.html?pageToInclude=RESULTS&type=fasttrack&AWB=',
		link_k024 : 'http://www.hanarologis.com/branch/chase/listbody.html?a_gb=center&a_cd=4&a_item=0&fr_slipno=',
		link_k025 : 'http://www.hbtb.co.kr/search/s_search.asp?f_slipno=',
		link_k026 : 'http://honam.enfrom.com/YYSearch/YYSearch.jsp?',
		link_ex01 : 'http://www.emspost.ru/ru/tracking/?id=',
	}
}());
